### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ineiti** [dedis/student_18_xplatform#43]
We need a nice logo for the app.

**Comment by richardbmx** [comment]
@ineiti  Hello my name is Richard I am a graphic designer and I love making contributions for open source projects, I see that you do not have a defined logo for your application. If you want I can do it for you without any problem you just have to authorize me to do it ... regards. ..

**Comment by ineiti** [comment]
Hi @richardbmx - sounds good to me! I'd love having a good logo ;) As from the description, this is what we're currently doing: https://pop.dedis.ch

Linus

**Comment by richardbmx** [comment]
@ineiti  perfect in general the project is about a system to determine if you are human or not within a certain web ??

**Comment by richardbmx** [comment]
@ineiti  I present my proposal the design is based on showing a security image for people that is why I use a shield with a human silhouette and I add the shape of a lock to represent easily and at first vita it is a project Security for the user.

If you want something to change or have an idea in mind do not hesitate to say it to make it



Variation Logotype

**Comment by richardbmx** [comment]
@ineiti  Have you seen the proposal of the logo?

**Comment by ineiti** [comment]
@richardbmx - thanks for the logo. We did use it for our app here: https://applivery.com/popcoin

We might change it soon, though ;)
