### ISSUE TITLE
Set app icon to the PoP icon

### ISSUE THREAD

**Issue by jeffallen** [dedis/student_18_xplatform#87]
Ask Linus for a SVG version, I could only find a bitmap (attached).

![untitled drawing 1](https://user-images.githubusercontent.com/1131456/44091713-a9665eac-9fce-11e8-9cdc-47b94b9bb730.png)

**Comment by jeffallen** [comment]
![untitled drawing 1](https://user-images.githubusercontent.com/1131456/44091713-a9665eac-9fce-11e8-9cdc-47b94b9bb730.png)

**Comment by ineiti** [comment]
got integrated in github.com/dedis/popcoins
